version: '3.7'

services:
  inventory:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: on-failure
    command: python3 manage.py runserver 0.0.0.0:8000

  postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=inventory_db
    restart: on-failure

volumes:
 postgres-data:
   driver: local
